import { nanoid } from "nanoid";

export const initialProducts = [
  {
    id: nanoid(),
    name: "Apple iPhone 14 Pro Max 128GB Deep Purple",
    category: "Phones",
    price: 900,
    oldPrice: 1050,
    image: "/itemsPhotos/Iphone 14 pro 1 (12).png",
    isNewArrival: true,
    screenSize: '6.7"',
    cpu: "Apple A16 Bionic",
    cores: 6,
    mainCamera: "48-12-12 MP",
    battery: "4323 mAh",
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    description:
      "Experience the magic of Dynamic Island, Always-On display, and a 48MP main camera for breathtaking detail.",
  },
  {
    id: nanoid(),
    name: "Blackmagic Pocket Cinema Camera 6k",
    category: "Electronics",
    price: 2535,
    oldPrice: 2700,
    image: "/itemsPhotos/Iphone 14 pro 1 (1).png",
    isNewArrival: true,
    screenSize: '5.0"',
    cpu: "Blackmagic OS",
    cores: 4,
    mainCamera: "6K Super 35 Sensor",
    battery: "LP-E6 (Removable)",
    storageOptions: ["CFast 2.0", "SD Card", "USB-C SSD"],
    description:
      "Features a massive 6K Super 35 sensor, EF lens mount, and dual native ISO up to 25,600 for cinematic digital film.",
  },
  {
    id: nanoid(),
    name: "Apple Watch Series 9 GPS 41mm Starlight",
    category: "Accessories",
    price: 399,
    oldPrice: 429,
    image: "/itemsPhotos/Iphone 14 pro 1 (13).png",
    isNewArrival: true,
    screenSize: '1.69" Retina',
    cpu: "Apple S9 SiP",
    cores: 2,
    mainCamera: "N/A",
    battery: "Up to 18 hours",
    storageOptions: ["64GB"],
    description:
      "Smarter, brighter, and faster. Featuring a magical new double tap gesture and a much brighter edge-to-edge display.",
  },
  {
    id: nanoid(),
    name: "AirPods Max Silver Starlight Aluminium",
    category: "Audio",
    price: 549,
    oldPrice: 599,
    image: "/itemsPhotos/Iphone 14 pro 1 (3).png",
    isNewArrival: true,
    screenSize: "N/A",
    cpu: "Apple H1 headphone chip (each ear)",
    cores: 10,
    mainCamera: "N/A",
    battery: "Up to 20 hours with ANC",
    storageOptions: ["Standard"],
    description:
      "A perfect balance of exhilarating high-fidelity audio and the effortless magic of AirPods. The ultimate over-ear headphone.",
  },
  {
    id: nanoid(),
    name: "Samsung Galaxy Watch6 Classic 47mm Black",
    category: "Accessories",
    price: 369,
    oldPrice: 419,
    image: "/itemsPhotos/Iphone 14 pro 1 (4).png",
    isNewArrival: true,
    screenSize: '1.5" Super AMOLED',
    cpu: "Exynos W930 Dual-Core",
    cores: 2,
    mainCamera: "N/A",
    battery: "425 mAh",
    storageOptions: ["16GB"],
    description:
      "Timeless look with a physical rotating bezel. Advanced sleep coaching, fitness tracking, and heart monitoring right on your wrist.",
  },
  {
    id: nanoid(),
    name: "Galaxy Z Fold5 Unlocked | 256GB | Phantom Black",
    category: "Phones",
    price: 1799,
    oldPrice: 1899,
    image: "/itemsPhotos/Iphone 14 pro 1 (5).png",
    isNewArrival: true,
    screenSize: '7.6" Main Foldable',
    cpu: "Snapdragon 8 Gen 2 for Galaxy",
    cores: 8,
    mainCamera: "50 MP + 12 MP + 10 MP",
    battery: "4400 mAh",
    storageOptions: ["256GB", "512GB", "1TB"],
    description:
      "Your pocket-sized movie theater, gaming console, and multi-tasking workstation all in one stunning foldable device.",
  },
  {
    id: nanoid(),
    name: "Galaxy Buds FE Graphite",
    category: "Audio",
    price: 99.99,
    oldPrice: 129.99,
    image: "/itemsPhotos/Iphone 14 pro 1 (6).png",
    isNewArrival: true,
    screenSize: "N/A",
    cpu: "Custom Samsung Chip",
    cores: 1,
    mainCamera: "N/A",
    battery: "Up to 30 hours total",
    storageOptions: ["Standard"],
    description:
      "Compact, ergonomic design with powerful Active Noise Cancellation (ANC) to help you tune out the world and tune into your music.",
  },
  {
    id: nanoid(),
    name: 'Apple iPad 9 10.2" 64GB Wi-Fi Silver (MK2L3) 2021',
    category: "Tablets",
    price: 398,
    oldPrice: 429,
    image: "/itemsPhotos/Iphone 14 pro 1 (7).png",
    isNewArrival: true,
    screenSize: '10.2" Retina',
    cpu: "A13 Bionic chip",
    cores: 6,
    mainCamera: "12MP Ultra Wide",
    battery: "Up to 10 hours",
    storageOptions: ["64GB", "256GB"],
    description:
      "Powerful, easy to use, and versatile. Designed for all the things you do everyday with a gorgeous Retina display.",
  },
  {
    id: nanoid(),
    name: "Apple iPad Pro 12.9-inch Liquid Retina XDR",
    category: "Tablets",
    price: 1099,
    oldPrice: 1199,
    image: "/itemsPhotos/Iphone 14 pro 1 (14).png",
    isNewArrival: false,
    screenSize: '12.9" Liquid Retina XDR',
    cpu: "Apple M2 chip",
    cores: 8,
    mainCamera: "12MP Wide + 10MP Ultra Wide",
    battery: "40.88 Wh",
    storageOptions: ["128GB", "256GB", "512GB", "1TB", "2TB"],
    description:
      "Ultimate iPad experience with groundbreaking M2 performance, a breathtaking XDR display, and blazing-fast wireless connectivity.",
  },
  {
    id: nanoid(),
    name: "Samsung Galaxy Z Fold4 Phantom Black",
    category: "Phones",
    price: 1599,
    oldPrice: 1799,
    image: "/itemsPhotos/Iphone 14 pro 1 (16).png",
    isNewArrival: false,
    screenSize: '7.6" Dynamic AMOLED 2X',
    cpu: "Snapdragon 8+ Gen 1",
    cores: 8,
    mainCamera: "50 MP Wide",
    battery: "4400 mAh",
    storageOptions: ["256GB", "512GB"],
    description:
      "Durable foldable phone that stands up, writes down, and opens up to a tablet-sized screen for ultimate productivity.",
  },
  {
    id: nanoid(),
    name: "Apple MacBook Pro 16 M3 Max Space Black",
    category: "Laptops",
    price: 2499,
    oldPrice: 2699,
    image: "/itemsPhotos/Macbook 1.png",
    isNewArrival: false,
    screenSize: '16.2" Liquid Retina XDR',
    cpu: "Apple M3 Max",
    cores: 16,
    mainCamera: "1080p FaceTime HD",
    battery: "100 Wh",
    storageOptions: ["1TB", "2TB", "4TB", "8TB"],
    description:
      "A beast of a laptop built for extreme workflows, featuring the M3 Max chip, stunning battery life, and a gorgeous Space Black finish.",
  },
  {
    id: nanoid(),
    name: "Apple iPhone 14 Pro 512GB Gold (MQ233)",
    category: "Phones",
    price: 1437,
    oldPrice: 1550,
    image: "/itemsPhotos/75e9511b54189b8ee3104a701ea71c524e6521e4.png",
    isNewArrival: false,
    screenSize: '6.7"',
    cpu: "Apple A16 Bionic",
    cores: 6,
    mainCamera: "48 MP Main",
    battery: "4323 mAh",
    storageOptions: ["512GB"],
    description:
      "Luxurious Gold edition with 512GB storage, always-on display, and professional-grade mobile photography features.",
  },
  {
    id: nanoid(),
    name: "Apple iPhone 11 128GB White (MQ233)",
    category: "Phones",
    price: 510,
    oldPrice: 580,
    image: "/itemsPhotos/34cebf757f8dea2a7d3639bb78713105f1431309 (1).png",
    isNewArrival: false,
    screenSize: '6.1" Liquid Retina',
    cpu: "Apple A13 Bionic",
    cores: 6,
    mainCamera: "Dual 12MP Ultra Wide & Wide",
    battery: "3110 mAh",
    storageOptions: ["64GB", "128GB", "256GB"],
    description:
      "Classic white design with a reliable dual-camera system, all-day battery life, and tough glass construction.",
  },
  {
    id: nanoid(),
    name: "Apple iPhone 14 Pro 1TB Gold (MQ2V3)",
    category: "Phones",
    price: 1499,
    oldPrice: 1650,
    image: "/itemsPhotos/75e9511b54189b8ee3104a701ea71c524e6521e4.png",
    isNewArrival: false,
    screenSize: '6.7"',
    cpu: "Apple A16 Bionic",
    cores: 6,
    mainCamera: "48 MP Main",
    battery: "4323 mAh",
    storageOptions: ["1TB"],
    description:
      "Massive 1TB storage capacity combined with Apple's top-tier A16 Bionic performance and a gorgeous Gold finish.",
  },
  {
    id: nanoid(),
    name: "Apple iPhone 14 Pro 128GB Deep Purple (MQ0G3)",
    category: "Phones",
    price: 1600,
    oldPrice: 1750,
    image: "/itemsPhotos/0123832569250cc2de152232d881e44b747d3e55.png",
    isNewArrival: false,
    screenSize: '6.7"',
    cpu: "Apple A16 Bionic",
    cores: 6,
    mainCamera: "48 MP Main",
    battery: "4323 mAh",
    storageOptions: ["128GB"],
    description:
      "Deep Purple flagship device featuring ProMotion technology, Crash Detection, and an advanced 48MP camera system.",
  },
  {
    id: nanoid(),
    name: "Apple iPhone 13 mini 128GB Pink (MLK23)",
    category: "Phones",
    price: 850,
    oldPrice: 920,
    image: "/itemsPhotos/6cfe0b09d9117ef7d870d16c2ee487ae54daf98a.png",
    isNewArrival: false,
    screenSize: '5.4" Super Retina XDR',
    cpu: "Apple A15 Bionic",
    cores: 6,
    mainCamera: "Dual 12MP",
    battery: "2438 mAh",
    storageOptions: ["128GB", "256GB", "512GB"],
    description:
      "Pocket-friendly size packed with big performance, stunning pink finish, and cinematic video recording modes.",
  },
  {
    id: nanoid(),
    name: "Apple iPhone 14 Pro 256GB Space Black (MQ0T3)",
    category: "Phones",
    price: 1399,
    oldPrice: 1499,
    image: "/itemsPhotos/2b12e06b5f2b9bbd5cdc31ba14fe87f3c707b098.png",
    isNewArrival: false,
    screenSize: '6.7"',
    cpu: "Apple A16 Bionic",
    cores: 6,
    mainCamera: "48 MP Main",
    battery: "4323 mAh",
    storageOptions: ["256GB"],
    description:
      "Sleek Space Black color with 256GB storage, smooth 120Hz display refresh rate, and professional features.",
  },
  {
    id: nanoid(),
    name: "Apple iPhone 14 Pro 256GB Silver (MQ10)",
    category: "Phones",
    price: 1399,
    oldPrice: 1499,
    image: "/itemsPhotos/91a91f9fa51ffe2dcd3c8c730f33e506dd49f245 (1).png",
    isNewArrival: false,
    screenSize: '6.7"',
    cpu: "Apple A16 Bionic",
    cores: 6,
    mainCamera: "48 MP Main",
    battery: "4323 mAh",
    storageOptions: ["256GB"],
    description:
      "Elegant Silver edition with 256GB of storage, robust ceramic shield front, and incredible battery efficiency.",
  },
];
